version: '3'

services:
  app:
    build: 
      context: node
    container_name: app
    networks:
      - nginx-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge